version: '2'
services:
  bitmark-node:
    environment:
      - PUBLIC_IP=127.0.0.1
    build: .
    volumes:
      - /path/to/bitmarkd/data:/.config/bitmark-node/bitmarkd/bitmark/data
      - /path/to/bitmarkd/data-test:/.config/bitmark-node/bitmarkd/testing/data
    ports:
      - "0.0.0.0:2130:2130"
      - "0.0.0.0:2131:2131"
      - "0.0.0.0:2135:2135"
      - "0.0.0.0:2136:2136"
      - "0.0.0.0:2150:2150"
      - "0.0.0.0:8080:9980"
